# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=500)),
                ('style', models.CharField(max_length=100)),
                ('date_of_release', models.DateField()),
                ('total_duration', models.CharField(max_length=100)),
                ('album_logo', models.CharField(max_length=1000)),
                ('profile', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=4000)),
                ('is_band', models.BooleanField()),
                ('artist_photo', models.CharField(max_length=1000)),
                ('profile', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Record_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=250)),
                ('founding', models.DateField()),
                ('profile', models.CharField(max_length=1000)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('date_of_release', models.DateField()),
                ('total_duration', models.CharField(max_length=100)),
                ('song_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Song'),
        ),
    ]
