# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161229_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
